import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from collections import Counter

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Sugar Trap — Market Gap Analyzer",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Constants (must match notebook) ──────────────────────────────────────────
DATA_URL = "https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz"
RELEVANT_COLS = [
    "product_name", "categories_tags",
    "sugars_100g", "proteins_100g",
    "fat_100g", "fiber_100g",
    "energy_100g", "ingredients_text",
]
PROTEIN_THRESHOLD = 10.0
SUGAR_THRESHOLD   = 5.0
PLOT_SAMPLE       = 30_000  # lower than notebook for web rendering

CATEGORY_MAP = {
    "Snacks & Crisps":     ["snack", "crisp", "chip", "popcorn", "pretzel", "cracker"],
    "Baked Goods":         ["biscuit", "cake", "cookie", "bread", "pastry", "wafer", "muffin", "brownie"],
    "Dairy & Eggs":        ["dairy", "cheese", "yogurt", "yoghurt", "milk", "egg", "cream"],
    "Beverages":           ["beverage", "drink", "juice", "water", "soda", "smoothie", "tea", "coffee"],
    "Protein Foods":       ["protein", "meat", "fish", "chicken", "beef", "whey", "bar", "shake"],
    "Confectionery":       ["chocolate", "candy", "sweet", "sugar", "caramel", "gum", "lolly"],
    "Cereals & Grains":    ["cereal", "granola", "oat", "grain", "muesli", "porridge", "rice"],
    "Fruits & Vegetables": ["fruit", "vegetable", "nut", "seed", "dried", "berry"],
    "Prepared & Packaged": ["prepared", "canned", "frozen", "instant", "soup", "sauce",
                            "condiment", "spread", "pasta", "noodle", "meal", "salad",
                            "seasoning", "dressing", "jam", "honey", "syrup"],
}
OTHER = "Other"

PROTEIN_KEYWORDS = [
    "whey", "casein", "pea protein", "soy protein", "soy isolate",
    "milk protein", "egg white", "hemp protein", "collagen",
    "chickpea", "lentil", "quinoa", "almonds", "cashews", "peanut",
]


# ── Helper functions (identical logic to notebook) ────────────────────────────
def _assign_category(tags: str) -> str:
    if not isinstance(tags, str) or not tags.strip():
        return OTHER
    tl = tags.lower()
    for cat, kws in CATEGORY_MAP.items():
        if any(kw in tl for kw in kws):
            return cat
    return OTHER


def _compute_hsi(df: pd.DataFrame) -> pd.Series:
    def minmax(s):
        rng = s.max() - s.min()
        return (s - s.min()) / (rng if rng > 0 else 1.0)
    return (
        minmax(df["proteins_100g"]) * 0.35
        + minmax(df["fiber_100g"])  * 0.30
        - minmax(df["sugars_100g"]) * 0.25
        - minmax(df["fat_100g"])    * 0.10
    )


# ── Data loading ──────────────────────────────────────────────────────────────
@st.cache_data(show_spinner="Loading data — this takes ~2 min on first run...")
def load_data() -> pd.DataFrame:
    # Fast path: local summary CSV generated by the notebook
    try:
        df = pd.read_csv("sugar_trap_summary.csv")
        if "health_score" not in df.columns:
            df["health_score"] = _compute_hsi(df)
        return df
    except FileNotFoundError:
        pass

    # Slow path: download from OpenFoodFacts (capped at 100k rows for Streamlit Cloud)
    try:
        df_raw = pd.read_csv(
            DATA_URL,
            usecols=RELEVANT_COLS,
            nrows=100_000,
            low_memory=False,
            sep="\t",
            on_bad_lines="skip",
        )
    except Exception as e:
        st.error(f"Failed to load data from OpenFoodFacts: {e}")
        st.stop()

    required = ["product_name", "sugars_100g", "proteins_100g"]
    df = df_raw.dropna(subset=required).copy()
    for col in ["sugars_100g", "proteins_100g", "fat_100g", "fiber_100g"]:
        if col in df.columns:
            df = df[df[col].between(0, 100)]
    for col in ["fat_100g", "fiber_100g", "energy_100g"]:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].median())
    df = df.drop_duplicates(subset="product_name", keep="first")
    df["primary_category"] = df["categories_tags"].apply(_assign_category)
    df["health_score"] = _compute_hsi(df)
    return df


df = load_data()

# ── Sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.title("Filters")
st.sidebar.markdown("---")

all_categories = sorted(df["primary_category"].unique().tolist())
selected_categories = st.sidebar.multiselect(
    "Filter by Category",
    options=all_categories,
    default=all_categories,
    placeholder="Select categories...",
)

protein_min = st.sidebar.slider("Min Protein (g/100g)", 0.0, 50.0, 0.0, step=0.5)
sugar_max   = st.sidebar.slider("Max Sugar (g/100g)",   0.0, 100.0, 100.0, step=0.5)
blue_ocean_only = st.sidebar.checkbox("Show Blue Ocean products only", value=False)

st.sidebar.markdown("---")
st.sidebar.caption(
    "Data: [Open Food Facts](https://world.openfoodfacts.org) (CC BY-SA 4.0).  \n"
    "Analysis: Sugar Trap v1.0 · Helix CPG Partners"
)

# ── Apply filters ─────────────────────────────────────────────────────────────
df_filtered = df[
    df["primary_category"].isin(selected_categories) &
    (df["proteins_100g"] >= protein_min) &
    (df["sugars_100g"] <= sugar_max)
]
if blue_ocean_only:
    df_filtered = df_filtered[
        (df_filtered["proteins_100g"] > PROTEIN_THRESHOLD) &
        (df_filtered["sugars_100g"] < SUGAR_THRESHOLD)
    ]

blue_ocean = df_filtered[
    (df_filtered["proteins_100g"] > PROTEIN_THRESHOLD) &
    (df_filtered["sugars_100g"] < SUGAR_THRESHOLD)
]

# ── Header ────────────────────────────────────────────────────────────────────
st.title("Sugar Trap — Snack Market Gap Analysis")
st.markdown(
    "Explore the **Blue Ocean quadrant**: products with high protein and low sugar "
    "that are currently under-served in the snack market."
)

# ── KPI row ───────────────────────────────────────────────────────────────────
c1, c2, c3, c4 = st.columns(4)
total = max(len(df_filtered), 1)
c1.metric("Total Products",       f"{len(df_filtered):,}")
c2.metric("Blue Ocean Products",  f"{len(blue_ocean):,}")
c3.metric("Blue Ocean %",         f"{len(blue_ocean)/total*100:.1f}%")
c4.metric("Categories Shown",     f"{df_filtered['primary_category'].nunique()}")

st.markdown("---")

# ── Scatter plot ──────────────────────────────────────────────────────────────
df_plot = df_filtered.sample(min(PLOT_SAMPLE, len(df_filtered)), random_state=42)

fig = px.scatter(
    df_plot,
    x="sugars_100g",
    y="proteins_100g",
    color="primary_category",
    hover_name="product_name",
    hover_data={
        "sugars_100g": ":.1f",
        "proteins_100g": ":.1f",
        "health_score": ":.3f",
        "primary_category": False,
    },
    opacity=0.45,
    title="Nutrient Matrix: Sugar vs. Protein by Category",
    labels={
        "sugars_100g": "Sugar (g per 100g)",
        "proteins_100g": "Protein (g per 100g)",
        "primary_category": "Category",
    },
    color_discrete_sequence=px.colors.qualitative.Bold,
)
fig.add_shape(
    type="rect",
    x0=0, y0=PROTEIN_THRESHOLD,
    x1=SUGAR_THRESHOLD, y1=60,
    line=dict(color="green", width=2, dash="dash"),
    fillcolor="rgba(0,200,0,0.06)",
)
fig.add_annotation(
    x=SUGAR_THRESHOLD / 2, y=PROTEIN_THRESHOLD + 3,
    text="BLUE OCEAN",
    showarrow=False,
    font=dict(color="green", size=11, family="Arial Black"),
)
fig.update_traces(marker=dict(size=4))
fig.update_layout(
    xaxis_range=[0, 60],
    yaxis_range=[0, 60],
    height=550,
    legend=dict(orientation="v", x=1.01, y=0.5),
)
st.plotly_chart(fig, use_container_width=True)

# ── Key Insight box ───────────────────────────────────────────────────────────
st.markdown("### Key Insight")
if len(blue_ocean) > 0:
    cat_bo_counts = blue_ocean["primary_category"].value_counts()
    cat_totals    = df_filtered["primary_category"].value_counts()
    gap_ratio     = cat_bo_counts / cat_totals.reindex(cat_bo_counts.index).fillna(1)
    filtered_gap  = gap_ratio[gap_ratio.index != OTHER]

    if len(filtered_gap) > 0:
        top_cat   = filtered_gap.idxmin()
        top_prods = blue_ocean[blue_ocean["primary_category"] == top_cat]
        avg_p     = top_prods["proteins_100g"].mean()
        avg_s     = top_prods["sugars_100g"].mean()
        gap_pct   = (1 - gap_ratio[top_cat]) * 100

        st.info(
            f"Based on the data, the biggest market opportunity is in **{top_cat}**, "
            f"specifically targeting products with **{avg_p:.0f}g of protein** "
            f"and less than **{avg_s:.0f}g of sugar**. "
            f"Currently {gap_pct:.0f}% of {top_cat} products do NOT meet Blue Ocean "
            f"criteria — a large under-served segment for health-focused innovation."
        )
    else:
        st.info("All Blue Ocean products fall in the 'Other' category. Try broadening your filters.")
else:
    st.warning("No Blue Ocean products visible with current filters. Try relaxing the sliders.")

# ── HSI Leaderboard ───────────────────────────────────────────────────────────
st.markdown("---")
st.markdown("### Candidate's Choice: Health Score Index (HSI) by Category")
st.caption(
    "HSI = weighted composite of protein (+35%), fiber (+30%), sugar (−25%), fat (−10%). "
    "A single number lets stakeholders compare categories without reading a 4-axis chart."
)

cat_hsi = (
    df_filtered.groupby("primary_category")["health_score"]
    .agg(mean="mean", count="count")
    .query("count >= 20")
    .sort_values("mean", ascending=False)
    .reset_index()
)

if len(cat_hsi) >= 2:
    fig_hsi = px.bar(
        cat_hsi,
        x="primary_category",
        y="mean",
        color="mean",
        color_continuous_scale="RdYlGn",
        labels={"primary_category": "Category", "mean": "Average HSI"},
        title="Which categories score best on the Health Score Index?",
        text="mean",
    )
    fig_hsi.update_traces(texttemplate="%{text:.2f}", textposition="outside")
    fig_hsi.update_layout(coloraxis_showscale=False, height=380)
    st.plotly_chart(fig_hsi, use_container_width=True)
else:
    st.info("Not enough data for HSI chart with current filters.")

# ── Protein Source Analysis ───────────────────────────────────────────────────
st.markdown("---")
st.markdown("### Bonus: Top Protein Sources in Blue Ocean Products")

if "ingredients_text" in df.columns and len(blue_ocean) > 0:
    bo_with_ing = blue_ocean.dropna(subset=["ingredients_text"])
    all_sources: list = []
    for text in bo_with_ing["ingredients_text"]:
        tl = text.lower()
        all_sources.extend([kw for kw in PROTEIN_KEYWORDS if kw in tl])

    src_counts = Counter(all_sources)
    if src_counts:
        top3 = src_counts.most_common(3)
        labels, values = zip(*src_counts.most_common(12))
        fig_ing = px.bar(
            x=list(values), y=list(labels),
            orientation="h",
            title="Most Common Protein Sources in Blue Ocean Products",
            labels={"x": "Product Count", "y": "Ingredient"},
            color=list(values),
            color_continuous_scale="Blues",
        )
        fig_ing.update_layout(
            yaxis={"categoryorder": "total ascending"},
            showlegend=False, height=380,
        )
        st.plotly_chart(fig_ing, use_container_width=True)
        st.caption(
            "**Top 3 protein sources:** "
            + " · ".join(f"**{s.title()}** ({c} products)" for s, c in top3)
        )
    else:
        st.info("No matching protein keywords found in the current Blue Ocean selection.")
else:
    st.info(
        "Ingredient analysis requires the `ingredients_text` column. "
        "Load the full dataset from the notebook to enable this feature."
    )

st.markdown("---")
st.caption("Sugar Trap v1.0 · Built for Helix CPG Partners · Data: Open Food Facts (CC BY-SA 4.0)")
